### ISSUE TITLE
Mythtranscode "unsupported codec 3"

### ISSUE THREAD

**Issue by kdupke** [MythTV/mythtv#799] opened 2023-09-22 13:49 UTC
* **Platform**:
* ```
cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
```
```
uname -a
Linux koma 6.5.3-lp154.5.g89de233-default #1 SMP PREEMPT_DYNAMIC Fri Sep 15 15:09:42 UTC 2023 (89de233) x86_64 x86_64 x86_64 GNU/Linux
```

* **MythTV version**:
```
rpm -qf /usr/bin/mythtranscode
mythtv-common-31.0+git20210808.5da2523154-pm153.1.10.x86_64
```

* **Component**:
mythtranscode

### What steps will reproduce the bug?

```
mythtranscode --infile /Mythtv/mythtvB/data/2793_20180422180500.ts --honorcutlist --mpeg2  --showprogress -v
2023-09-22 15:36:37.213823 C  mythtranscode version:  [v31.0] www.mythtv.org
2023-09-22 15:36:37.213832 C  Qt version: compile: 5.12.7, runtime: 5.12.7
2023-09-22 15:36:38.237728 E  Error Loading en_us translation for module mythfrontend
2023-09-22 15:36:38.242273 E  Skipping unsupported codec 3 on stream 0
```
```

file /Mythtv/mythtvB/data/2793_20180422180500.ts
/Mythtv/mythtvB/data/2793_20180422180500.ts: MPEG transport stream data
```

```
mplayer /Mythtv/mythtvB/data/2793_20180422180500.ts
MPlayer 1.2.r38304-Packman-7 (C) 2000-2021 MPlayer Team

Playing /Mythtv/mythtvB/data/2793_20180422180500.ts.
libavformat version 58.76.100 (external)
TS file format detected.
VIDEO MPEG2(pid=2047) AUDIO A52(pid=2051) SUB Teletext(pid=36)  PROGRAM N. 1
VIDEO:  MPEG2  720x576  (aspect 3)  25.000 fps  15000.0 kbps (1875.0 kbyte/s)
```
### How often does it reproduce? Is there a required condition?
Always

### What is the expected behaviour?
I added cutting points via the frontend and tried to transcode this to get a recording without the unneeded content. As this did not work, and the backend claims the transcode job is still endless working, I tried this from the command line. Unfortunately I got the error message as listed above.

### What do you see instead?
Error message as quoted above.

**Comment by rcrdnalor** [comment] 2023-09-28 18:08
The message "Skipping unsupported codec 3 on stream x" is a red herring for this bug report.
Mythtranscode in mpeg2 mode uses only video and audio streams.
According the enum in https://github.com/MythTV/mythtv/blob/271b7ed8d/mythtv/external/FFmpeg/libavutil/avutil.h#L199
the skipped stream is dedicated to subtitle.
If you set the loglevel to loglevel INFO, then you probably would see something like:

`(AFD) Stream #0:2[0x27](deu): Subtitle: dvb_teletext`.
`(InitAV) Skipping unsupported codec 3 on stream 2`

Because you probably record always from sources airing subtitles as well (dvb-teletext),
you see this message on every transcode.  

The provided command line example is incorrect:
See 
 - mythtranscode --help
 - mythtranscode -v help

for correct usage of mythtranscode on the command line

MythTV v.31 is not supported anymore, making this issue hard to reproduce.
Issues should be raised against the current release (v.33) or against mythtv/git master (v34-Pre).

I closing this issue as mistaken.

Please ask the support forum at https://forum.mythtv.org/
or the user mailing list at http://lists.mythtv.org/mailman/listinfo/mythtv-users/
for additional support.
Be prepared to provide better logs as posted in this issue.

**Closed by rcrdnalor** 2023-09-28 18:08 UTC
