### ISSUE TITLE
Android inactivity issue

### ISSUE THREAD

**Issue by masjerang** [MythTV/mythtv#279] opened 2020-11-05 19:50 UTC
* **Platform**: Nvidia Shield, latest version

* **MythTV version**: fixes/31, latest, 32-bit

* **Package version**: mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk

* **Component**: Frontend Playback

### What steps will reproduce the bug?

During Playback of a recording, pause the playback and wait until Android screensaver kicks in.
Wake up the Shield, and MythFrontend has exited playback.
This happen every time the Shield activates screensaver. 
Expected behavior (two-fold):
1. Recover from inactivity and press Play, and continue playing where we left. 
or
2. Stop playback, but create a bookmark before exiting

In commit **627c03d** it is stated the Frontend gets into a bad unrecoverable state, but I'm not able to reproduce this. Reverting this patch, gives me no unrecoverable state and works most of the time. This does not work if Shield is turned off. Frontend restarts if Shield has been off for some time.

See also https://forum.mythtv.org/viewtopic.php?f=47&t=4015

**Comment by bennettpeter** [comment] 2020-11-10 19:44
Please make sure that you have the option to set bookmark on exit of playback (frontend ->setup -> Video -> Playback -> General playback -> Action on playback exit -> Save and Exit)

When you press "home" on the remote (Circle button) it returns to the android menu. If you press "home" while playback is paused, it should be the same as the screen saver starting. I tested with pressing home while playback paused and it does set a bookmark so that when you start play again it resumes from where it was.

Please check on your system if "home" has a different effect from screen saver, or whether you have this problem with pressing "home" as well.

**Comment by masjerang** [comment] 2020-11-11 21:08
Thanks Peter, that setting was not active on my system. This helps to get around the main issue.

My use case is that I pause the playback, screensaver kicks in after a few minutes and I would like to continue playing by unpausing. This works with the reverted commit mentioned above. The commit talks about unrecoverable state. Exiting Playback is probably getting around the unrecoverable state and saving the bookmark makes it easy to continue, but does not fix the unrecoverable state. For me it works with the reverted commit and/or with the additional setting, but I'm also happy to debug and fix the mentioned unrecoverable state.

**Comment by mspieth** [comment] 2020-11-12 00:17
I think the root cause now with pause and screensaver/switch app is that the opengl context is deleted when this happens and is not restored on refocus app. This causes black screens to occur if you are lucky. The only way to fix this is to config->apps->mythtv->force stop. and then restart.

When markk is done with things and has bandwidth we might try to address this problem. Recreating the opengl context the same way it was before it was silently removed may be difficult.

**Comment by bennettpeter** [comment] 2020-11-12 16:03
Closing this as it works as designed.

**Closed by bennettpeter** 2020-11-12 16:03 UTC
Labels: bug:general, component:mythtv:playback, version:v31-fixes
