### ISSUE TITLE
mythweb/utils.php/get_template_file

### ISSUE THREAD

**Issue by royboy626** [MythTV/mythtv#508] opened 2022-02-28 13:27 UTC
* **Platform**:

* **MythTV version**:

* **Package version**:

* **Component**:

**Comment by royboy626** [comment] 2022-02-28 13:37
[utils.php.patch.txt](https://github.com/MythTV/mythtv/files/8153643/utils.php.patch.txt)
function get_template_file in mythweb/includes/utils.php returns a warning with PHP 7.4. In  PHP 8.0, this is now an error. Submitted patch is compatible with both versions of PHP, returning the proper value. Using mythweb pulled via git with this patch restores mythweb functionality.

diff utils.php utils-new.php > utils.php.patch.txt
Patch applied from the includes directory (or an easy manual edit):
patch -p0 utils.php  < utils.php.patch.txt

**Comment by bennettpeter** [comment] 2022-02-28 14:06
I have been running php 8.0 since December without problems.
What action causes an error and what error do you see?

**Comment by rcrdnalor** [comment] 2022-03-08 20:34
Looking at the original code in question,

```
// Template finder helper
    function get_template_file($module, $file) {
    	$tmpl = tmpl;
        if (tmpl == 'tmpl')
            $tmpl = 'default';

        return "modules/{$module}/tmpl/{$tmpl}/{$file}";
    }
```
the intention of the author of MythWeb was to check a constant named "tmpl"
wether it is defined or not. If it is not defined, use the 'default' template.
The way the check is performed is deprecated since php7 and throws an error in php8.

See https://www.php.net/manual/en/language.constants.syntax.php :
If an undefined constant is used an Error is thrown. Prior to PHP 8.0.0, undefined
constants would be interpreted as a bare word string, i.e. (CONSTANT vs "CONSTANT").

During initialization of mythweb, this constant is set at a late state
(in file 'includes/skin.php' included from 'includes/init.php').
Note: php treats constants as global.

The code in question is only called if a (fatal) error occurs.

In other words, the observed error is not shown if the init phase succeded.
See https://forum.mythtv.org/viewtopic.php?f=29&t=4328&hilit=fatal+error
This explains, why we could not reproduce it easily.

Neither the attached patch of the OP nor the entry on the wiki page
https://www.mythtv.org/wiki/MythWeb#Mythweb_and_PHP_8.0
follow the intention of the author:
The proposed code for 'function get_template_file' is just a complicated
way to always select the 'default' template.

I suggest the follwing change, which is compatible to php7 and php8:
```
// Template finder helper
    function get_template_file($module, $file) {
        if (defined('tmpl')) {
            $tmpl = tmpl;
        } else {
            $tmpl = 'default';
        }

        return "modules/{$module}/tmpl/{$tmpl}/{$file}";
    }
```
Since the OP has not provided a way how to provoke this error, I could not test
the new implementation so far. Furthermore, I do not speak php.

Reviews are welcome, maybe @mymatenige, could you please look into it as well?

BTW this issue belongs to mythweb ( https://github.com/MythTV/mythweb ),
not to mythtv.

**Comment by mymatenige** [comment] 2022-03-08 20:38
I'm happy to take a look, but can you please provide the steps required to reproduce the bug?  The template above is empty.

**Comment by mymatenige** [comment] 2022-03-08 20:42
... and the suggested change looks fine.  Do you have a pull request?  I'll happily throw something together if required.

**Comment by rcrdnalor** [comment] 2022-03-08 20:55
@mymatenige I am not sure if solving this bug in the way I mentioned above exposes a lot of hidden ones.
Maybe it is a wise decision, to bind the error headers and footers always to the default template.
   
@royboy626 Please provide the steps required to reproduce this bug.

**Comment by mymatenige** [comment] 2022-03-11 21:08
It looks fine to me.  Given that modules/_shared/tmpl/tmpl/header.php has 

define('tmpl', 'default');

The authors intention looks as you've interpreted it.  At this time MythWeb is being kept alive rather than improved, so I think that the patch you've suggested looks fine.  However ... I'm not sure how you'd trigger this error as described by the OP (?).

I'll raise a pull request on the correct repo.

**Comment by mymatenige** [comment] 2022-03-11 21:22
This issue can be closed in favour of https://github.com/MythTV/mythweb/issues/79

**Comment by rcrdnalor** [comment] 2022-03-13 12:17
Issue https://github.com/MythTV/mythweb/issues/79 implemented.

**Closed by rcrdnalor** 2022-03-13 12:17 UTC
