### ISSUE TITLE
MySQL time zone support check fails after upgrading to MariaDB 10.6.3

### ISSUE THREAD

**Issue by JohnLBergqvist** [MythTV/mythtv#373] opened 2021-07-21 11:58 UTC
* **Platform**:
Arch Linux Server 5.10.52-1-lts SMP Tue, 20 Jul 2021 16:46:09 +0000 x86_64 GNU/Linux
* **MythTV version**:
MythTV Version : v31.0-158-g0680b37c68-dirty
* **Package version**:
N/A
* **Component**:
Backend/mythtv-setup
### What steps will reproduce the bug?
Upgrade to mariadb 10.6.3 and launch either the backend or mythtv-setup

### How often does it reproduce? Is there a required condition?
Every time.

### What is the expected behaviour?
The backend/setup should start normally.

### What do you see instead?
```
mythtv-setup -v database
...
2021-07-21 12:55:57.261045 I  MSqlQuery::exec(DBManager1) SELECT CONVERT_TZ(NOW(), 'SYSTEM', 'Etc/UTC') <<<< Took 0ms, Returned 1 row(s)
2021-07-21 12:55:57.261085 E  MySQL time zone support is missing.  Please install it and try again.  See 'mysql_tzinfo_to_sql' for assistance.
```

### Additional information

Running the following command both before & after the upgrade, returns the same result:
```
mysql -u mythtv -p mythconverg -e "SELECT CONVERT_TZ(NOW(), 'SYSTEM', 'Etc/UTC')"
Enter password: 
+----------------------------------------+
| CONVERT_TZ(NOW(), 'SYSTEM', 'Etc/UTC') |
+----------------------------------------+
| 2021-07-21 11:54:57                    |
+----------------------------------------+
```

Downgrading to the previous installed version of maraidb (10.5.9) fixes the problem for me. 
I am running pcre2 v10.37 both before and after the db upgrade.

**Comment by starvald** [comment] 2021-07-23 19:17
confirmed, mythbackend fails to start with 10.6.3. using arch linux too.

**Comment by keepitsimpleengineer** [comment] 2021-07-25 13:19
confirmed, mythbackend fails to start with 10.6.3.
Manjaro linux

**Comment by garybuhrmaster** [comment] 2021-07-25 20:17
This **may** (i.e. just a random guess) be related to intentional change in recent mariadb connector releases (ref: https://jira.mariadb.org/browse/CONC-509) which is impacting Qt's client version detection and support for prepared queries (ref:  https://bugreports.qt.io/browse/QTBUG-95071).

**Comment by keepitsimpleengineer** [comment] 2021-07-26 21:25
Additional note: after downgrading to mariadb 10.5.11-1, deleting recordings from 'Watch Recordings' does not work. They are removed from the selection list but return after refresh, and never appear in the 'System Status/AutoExpire List'.

**Comment by garybuhrmaster** [comment] 2021-07-26 21:50
> Additional note: after downgrading to mariadb 10.5.11-1, deleting recordings from 'Watch Recordings' does not work. They are removed from the selection list but return after refresh, and never appear in the 'System Status/AutoExpire List'.

Note that you cannot just downgrade the engine, you must remove the entire database instance (including all the files), as a database upgrade may change various (mariadb) system internals such that the only safe thing to do is restore to a newly initialized instance from the mythconverg backup you made just before upgrading the database engine (or from your most recent backup).

**Comment by stuarta** [comment] 2021-07-27 09:28
I can certainly reproduce the issue. I've tried a few things so far but no luck getting a usable test

**Comment by sm0svx** [comment] 2021-07-31 12:37
I also have this problem after upgrading my Arch server: mariadb 10.6.3-1.

Did some tests with the timezone support checking code. Changing [this code](https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythbase/dbutil.cpp#L869-L870) to
```
if (!query.exec("SELECT CONVERT_TZ(now(), 'SYSTEM', 'Etc/UTC')") || !query.next())
```
will make the test pass but most things in MythTV does not work and a lot of errors are printed in the log. Like:
```
2021-07-31 14:19:54.599288 E  DB Error (delta position map insert):
Query was:
INSERT INTO recordedseek (chanid, starttime, type, mark, offset) VALUES (2004,'2021-07-31T12:18:00Z',33,2544,101760),(2004,'2021-07-31T12:18:00Z',33,2564,102560),(2004,'2021-07-31T12:18:00Z',33,2584,103360),(2004,'2021-07-31T12:18:00Z',33,2604,104160),(2004,'2021-07-31T12:18:00Z',33,2624,104960),(2004,'2021-07-31T12:18:00Z',33,2644,105760),(2004,'2021-07-31T12:18:00Z',33,2665,106600),(2004,'2021-07-31T12:18:00Z',33,2685,107400),(2004,'2021-07-31T12:18:00Z',33,2711,108440),(2004,'2021-07-31T12:18:00Z',33,2731,109240),(2004,'2021-07-31T12:18:00Z',33,2750,110000),(2004,'2021-07-31T12:18:00Z',33,2770,110800)
Driver error was [2/1064]:
QMYSQL: Unable to execute query
Database error was:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'offset) VALUES (2004,'2021-07-31T12:18:00Z',33,2544,101760),(2004,'2021-07-31...' at line 1
```
Only one recording is found and it's actually playable but just about everything else seem messed up.

Seems like @garybuhrmaster is right about that there is some problem with prepared queries.

Time to downgrade MariaDB and restore the latest backup.

**Comment by garybuhrmaster** [comment] 2021-07-31 14:55
The issue with offset is thought to be fixed in the MythTV master branch (and it is to be expected that for those running a bleading edge distro such as arch you should expect to also need to run the master branch of MythTV where fixes are introduced).

A simplified test case for the convert_tz select did not misbehave on another distro running MariaDB 10.6, but fails on arch, so it is currently unclear what the underlying cause is.

**Comment by starvald** [comment] 2021-07-31 15:14
the Arch build script for mariadb is viewable, they don't seem to have done much apart from building what the mariadb devs released.
https://github.com/archlinux/svntogit-packages/tree/packages/mariadb/trunk

**Comment by sm0svx** [comment] 2021-07-31 16:50
Just tried master and unfortunately it still fail with mariadb 10.6.3 on Arch :-/
But I guess that is consistent with the simplified test that @garybuhrmaster talk about.

**Comment by garybuhrmaster** [comment] 2021-07-31 17:15
> Just tried master and unfortunately it still fail with mariadb 10.6.3 on Arch :-/
> But I guess that is consistent with the simplified test that @garybuhrmaster talk about.

Yes, master just fixes the use of the name offset issue (which will be needed for MariaDB 10.6 compatibility on any/all systems going forward as offset is a new reserved keyword), not the initially reported convert_tz select issue currently seen on arch, which, at initial review, does not seem to be a MythTV issue (the simplified test is independent of MythTV, although it does use the Qt APIs).

More work will need to be done to determine the underlying causes.

**Comment by sm0svx** [comment] 2021-07-31 18:37
Ok I see now PR #376. That should probably be applied to branch fixes/31 as well but I don't know what the MythTV project policy is on what goes into that branch. Alternatively it could be included in the [AUR package](https://aur.archlinux.org/packages/mythtv/) as a patch. But of course it's just half a solution at the moment.

**Comment by garybuhrmaster** [comment] 2021-07-31 23:52
> Ok I see now PR #376. That should probably be applied to branch fixes/31 as well 

It was generally thought at the time of the pull request that it would need to get back ported(*) but for those who choose to live on the bleeding edge, one must expect to use the equivalent bleeding edge upstream from other projects to get more timely fixes, or be prepared to do their own back-porting.

> But of course it's just half a solution at the moment.

The phrase I use is "necessary but not sufficient".

-----

(*) And, not unique to MythTV, many projects let new(er) fixes settle and get initial testing in a development branch to identify issues before even considering back-porting (since regressions happen).

**Comment by billmeek** [comment] 2021-08-01 03:17
Pushed the v31 cherry-picks 5824c58  46cf50b about 14:1:00 -0500.

**Comment by stuarta** [comment] 2021-08-03 10:17
As Gary mentioned this is reproducible outside of MythTV, hence i've tagged it as an upstream issue. 

Simplified reproducer (from @garybuhrmaster ), adjust DB credentials before building
```c++
#include <QtGui>
#include <QtSql>
 
int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
 
  QSqlDatabase db = QSqlDatabase::addDatabase("QMYSQL");
  db.setHostName("localhost");
  db.setDatabaseName("mydatabase");
  db.setUserName("myuser");
  db.setPassword("mypassword");
  bool ok = db.open();

  if(ok)
  {

    QSqlQuery query;
    query.prepare("SELECT CONVERT_TZ(NOW(), 'SYSTEM', 'Etc/UTC')");
    if (!query.exec() || !query.next())
    {
        qWarning() << "Time zone support check failed";
    }
    if (query.value(0).isNull())
    {
        qWarning() << "return was a null value (no timezone tables loaded)";
    }
    else
    {
        qWarning() << query.value(0).toString();
    }

  }
  else
  {
     qWarning() << "Failed to open database";
  }
}
```
with the `.pro` file as follows
```
QT += core gui sql
SOURCES += tzcheck.cpp
```

**Comment by billmeek** [comment] 2021-08-03 20:45
@garybuhrmaster, does the above fail if **Etc/UTC** is changed to **UCT**? Curious to know it it's a problem following the symbolic link. Works OK with Ubuntu 20.04.

**Comment by garybuhrmaster** [comment] 2021-08-03 22:52
> @garybuhrmaster, does the above fail if **Etc/UTC** is changed to **UCT**? Curious to know it it's a problem following the symbolic link.

The zone name(s) are properly in the time_zone... tables of which the data was generated by the external program (that decodes the zoneinfo files, and follows the links).  And manually issuing the select via the mysql cli returns a valid value.  It would appear that the issue is somewhere between MariaDB and Qt in that the returned value results in a NULL rather than a valid value.

Running MariaDB 10.6.3 (from the mariadb.org repo) with Fedora 34 seems to produce the correct result, and as you state that running MariaDB 10.6.3 in Ubuntu 20.04 produces the correct result, the finger points towards something different in arch.  It should be noted that there are many libraries that either/both Qt and MariaDB depend upon, so it may be one of those that is the actual underlying cause (and not MariaDB or Qt directly).

I would suggest that someone with an arch bug tracker userid open an issue there with the reproducer included here, and let arch experts investigate this upstream issue further.

**Comment by starvald** [comment] 2021-08-07 05:29
Arch dev figured it out.

https://bugreports.qt.io/browse/QTBUG-95639

**Comment by antonio-rojas** [comment] 2021-08-07 07:07
> This **may** (i.e. just a random guess) be related to intentional change in recent mariadb connector releases (ref: https://jira.mariadb.org/browse/CONC-509) which is impacting Qt's client version detection and support for prepared queries (ref: https://bugreports.qt.io/browse/QTBUG-95071).

Turns out it's related in a twisted, unexpected way: that bug causes Qt to misidentify 10.6 as and old version not supporting prepared queries, so this bug (which affects prepared queries) doesn't happen in unpatched Qt. Arch is shipping a patch to workaround QTBUG-95071, which explains why this is only noticeable on Arch and derivatives.

**Comment by antonio-rojas** [comment] 2021-08-14 08:14
Fixed in Qt with https://codereview.qt-project.org/c/qt/qtbase/+/364843

**Comment by starvald** [comment] 2021-08-14 08:52
confirmed, updated qt-base and mariadb (to 10.6.4) in Arch and mythbackend loads correctly.

**Comment by stuarta** [comment] 2021-08-17 09:48
Reported as resolved with latest Arch updates to the relevant package

**Closed by stuarta** 2021-08-17 09:48 UTC
Labels: version:master, version:v31-fixes, upstream
