### ISSUE TITLE
TheTVDB V4 is not providing Release Date for TV episodes

### ISSUE THREAD

**Issue by bennettpeter** [MythTV/mythtv#628] opened 2022-08-25 00:35 UTC
* **Platform**: Xubuntu 22.04

* **MythTV version**: V32 and master

* **Package version**: v32.0-38-ga26786f5b4 and v33-Pre-845-g5dd3365db9

* **Component**: ttvdb4.py

### What steps will reproduce the bug?
Set Television Metadata Source as TheTVDatabaseV4
Add a video file directory and file to your videos storage group named Big Sky (2020)/S02E10 Happy Thoughts.mkv
run mythutil --scanvideos.
In the database the video has Title, plot, etc. but release_date is null. Release date is present in the tv database if you look it up on the web page thetvdb.com

If you do the same but set Television Metadata source as TheMovieDB V3 and do the same test, you do get the release date, but you have to name the directory and file Big Sky/S02E10 Happy Thoughts.mkv because themoviedb does not recognize the year after the title.

Note that between tests you have to remove the Big Sky directory and scan without it so that the next time you add it and scan it will look it up again

### How often does it reproduce? Is there a required condition?
Every time

### What is the expected behaviour?
release_date filled in

### What do you see instead?
release_date is null

### Additional information
I need the release_date to be filled in so that it can be returned with the API. I use it for sorting episodes into correct sequence.

**Comment by rcrdnalor** [comment] 2022-08-26 18:24
The release date of an episode of a TV series is quite ambiguous.
It could be
 - the "first aired date" of this episode in your country
 - the date when the season of this episode is released/announced (locally or globally)
 - the date the series itself was announced/released (locally or globally)
 
Streaming companies might have different rules for this dates. 

Looking at MythTVs metadata definition at
https://www.mythtv.org/wiki/MythTV_Universal_Metadata_Format
the defined 'releasedate' is 'The release date for the returned item in RFC-822 format.'
Not really helpful.

The TheTVDB.com API at 
https://github.com/thetvdb/v4-api/blob/main/docs/swagger.yml
defines what dates are available:
 - the episode itself has an 'aired' attribute, without explaining that in detail
 - the corresponding season has a 'year' attribute 
 - the series itself has a 'firstAired' attribute.
 
All this attributes may depend from your 'locale' setting, i.e.: language and country.
Example: 'The Munsters' was first aired in 1964 in USA, but aired in Austria the first time at 1976.

The fact that the web interface at thetvdb.com returns a date for
each episode, does not mean that this date is suitable for you sort algorithm. 
 
Defining the "release date" as the "recent aired date" does not make any sense to me, too.
TV Stations tend to re-transmit popular series over and over again. 

Another very important aspect is that we need to align the different semantics
of the various TV grabbers (ttvdb4, tmdb3, tvmaze) in respect to the
mythconverg database entry 'releasedate' of a specific episode.

You wrote:
|| I need the release_date to be filled in so that it can be returned with the API.
|| I use it for sorting episodes into correct sequence.

Why not using the season and episode information returned by the MythTVs services?

Please explain what is the correct sequence to sort: e.g.:
 - episodes
 - seasons
 - series

I personally use the re-transmission of specific episodes to fill in gaps caused by missing episodes.
How does this fit into your process/way of sorting?

**Comment by bennettpeter** [comment] 2022-08-27 00:17
The date I am looking for is the date when the episode was first broadcast. This corresponds to the airdate that is received from the listings service, Schedules Direct, on reruns. For original runs, schedules direct does not include the airdate, and in that case the original airdate is the recording date. It also matches the date in the TV DB web page labeled "First Aired" for each episode.

The date for when the series was released is not useful as it is the same date for all episodes.

I would guess that the "aired" attribute is the one needed.

The reason I prefer the original air date to the season and episode for sorting, is that when sorting multiple series together, it does not make sense to use season and episode. In a sort of "all series" you want everything in the order it was aired, especially when there are crossovers between series. For example "Law and order special victims unit" Season 20 episode 25 may have a crossover with "Chicago PD" season 5 episode 15. Both of those woudl show on the same or consecutive dates. This type of thing happens from time to time.

mythfrontend allows sorting recordings by recording date or original air date. There are no such options for videos, they are always sorted by file name as far as I know.

In my "leanfront" frontend program, I am adding an option to merge the videos with the recordings in cases where the series title matches. When an episode is missed I can record it from the "on demand" cable service and add it to the video storage group. I create a directory name matching the title and file name matching the episode in the format SxxExx.mkv. Then running "mythutil --scanvideos" looks up the episode details, such as plot and artwork, and adds them to the MythTV database. Using tmdb3 does get me the original air date but ttvdb does not. I prefer to use ttvdb.

For now, in leanfront I am using the season and episode for merging videos with episodes, and I am not merging the "All Series" row that contains all series together, since using season and episode would not make sense.

Correct way to sort, in leanfront, for a recording group - 
1st row on the screen has all episodes from all series in airdate order. This is for people who want to watch everything, oldest stuff first.
Subsequent rows are one row per series name, alphabetically. In each row are episodes in airdate order of that series. Sorting by season and episode works the same as sorting by airdate for these rows.

**Comment by rcrdnalor** [comment] 2022-11-29 19:08
Fixed on master and fixes/32.
Closing that issue.

**Closed by rcrdnalor** 2022-11-29 19:08 UTC
Labels: version:master, component:mythtv:metadata, version:v32-fixes
