### ISSUE TITLE
Mythtranscode segmentation fault in v32

### ISSUE THREAD

**Issue by KungFuJesus** [MythTV/mythtv#560] opened 2022-05-10 19:09 UTC
* **Platform**: `Linux mythtvbox 5.17.5-gentoo #1 SMP PREEMPT Sun May 1 02:28:31 EDT 2022 x86_64 Intel(R) Core(TM)2 Quad CPU Q9650 @ 3.00GHz GenuineIntel GNU/Linux`

* **MythTV version**: fixes/32

* **Package version**:

* **Component**: Utilities

### What steps will reproduce the bug?

Attempt to transcode a video.

### How often does it reproduce? Is there a required condition?
Every time.

### What is the expected behaviour?
Successful transcode.

### What do you see instead?
Menu disappears without current fix to the UI but with it, segmentation fault.

### Additional information
I am not the OP here but this guy appears to have the same issue: https://forum.mythtv.org/viewtopic.php?f=36&t=4794&p=23541&hilit=mythtranscode#p23541

It sounds like he was able to fix the segfault by assigning a nop for a callback, but had additional issues where the video didn't properly transcode.  I searched on mailing list and this issue tracker and found no such mention of this so I figured I'd post it here.

**Comment by kmdewaal** [comment] 2022-06-23 20:37
Closing this issue as a duplicate of #581

**Closed by kmdewaal** 2022-06-23 20:37 UTC
